<?php
/**
 * @file
 * Code for the Knews feature.
 */

include_once 'knews.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function knews_ctools_plugin_directory($module, $plugin) {
  $modules = array('ctools');
  if (in_array($module, $modules)) {
    return $module . '/' . $plugin;
  }
}

// ============================================================================
// Taxonomy Menu

/**
 * Implements hook_taxonomy_menu_path().
 */
function knews_taxonomy_menu_path() {
  $output = array(
    'knews_taxonomy_menu_path_custom' => t('Custom (news/%knews_cat)'),
  );

  return $output;
}

/**
 * Callback for hook_taxonomy_menu_path.
 */
function knews_taxonomy_menu_path_custom($term) {
  $knews_cat = str_replace(' ', '-', drupal_strtolower($term->name));
  $path = 'news/' . $knews_cat;

  return $path;
}

// Add .active class to item
function knews_preprocess_views_view_list(&$vars) {
  $view = $vars['view'];
  //dsm($vars);
  if ($view->name == 'knews_category_navigation') {
    $current_path = current_path();
    if ($current_path != 'news' && KtoolsString::startsWith($current_path, 'news')) {
      $url = explode('/', $current_path);
      foreach ($view->result as $i => $term) {
        // @experience $vars['classes'] as structure array, $vars['classes_array'] is for product.
        $depth = $term->taxonomy_term_data_hdepth;
        $vars['classes'][$i][] = 'depth-' . $depth;
        $term_name = $term->taxonomy_term_data_name;
        if ($url[1] == str_replace(' ', '-', strtolower($term_name))) {
          $vars['classes'][$i][] = 'active';
        }
        // Finalize classes
        foreach ($vars['classes_array'] as $i => $classes) {
          $vars['classes_array'][$i] = implode(' ', $vars['classes'][$i]);
        }
      }
    }
  }
}
